pipeline {
    agent any
    environment {
        PYTHONPATH = "${WORKSPACE}/src"
    }

    stages {
        stage('Run Python Script') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'my_aws_account',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh "python3 src/run.py --initial-account-data-key hello"
                    sh "ls"
                    sh "pwd"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}